[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  functions = "netlify/functions"
  functionsPort = 8888
  publish = "dist"
  port = 8888
  targetPort = 8081
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA fallback - toutes les routes non-API redirigent vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 